# Generated by Django 5.2.3 on 2026-10-02 13:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0008_alter_profile_whatsapp_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="JamiiTekService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=140, unique=True)),
                (
                    "icon",
                    models.CharField(
                        default="bi-stars",
                        help_text="Bootstrap icon class, e.g. bi-globe2",
                        max_length=40,
                    ),
                ),
                ("tagline", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("benefits", models.TextField(help_text="One benefit per line")),
                (
                    "opportunities",
                    models.TextField(
                        blank=True,
                        help_text="Opportunities / who it is for, one per line",
                    ),
                ),
                (
                    "cta_label",
                    models.CharField(default="Wasiliana nasi", max_length=60),
                ),
                (
                    "cta_url",
                    models.URLField(
                        blank=True, help_text="Empty = WhatsApp link from settings"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("active", models.BooleanField(default=True)),
                ("last_featured_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "JamiiTek service",
                "ordering": ["order", "name"],
            },
        ),
        migrations.CreateModel(
            name="NewsBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("drafting", "Drafting"),
                            ("pending", "Awaiting approval"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        default="drafting",
                        max_length=12,
                    ),
                ),
                ("notes", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "approval",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="core.approvalrequest",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "News batches",
                "ordering": ["-date"],
            },
        ),
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=220, unique=True)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("dunia", "Dunia"),
                            ("afrika", "Afrika"),
                            ("tanzania", "Tanzania"),
                            ("jamiitek", "JamiiTek"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "excerpt",
                    models.CharField(
                        help_text="Meta description and card summary (≤160 chars ideal)",
                        max_length=300,
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        help_text="Paragraphs separated by a blank line; '## ' starts a subheading"
                    ),
                ),
                ("keywords", models.CharField(blank=True, max_length=300)),
                (
                    "sources",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text='[{"title": "", "url": "", "publisher": ""}]',
                    ),
                ),
                (
                    "source_url",
                    models.URLField(
                        blank=True,
                        help_text="Main source item — prevents writing the same story twice",
                        max_length=500,
                        null=True,
                        unique=True,
                    ),
                ),
                (
                    "slot",
                    models.PositiveSmallIntegerField(
                        default=0, help_text="Position within the day's batch"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("rejected", "Rejected"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=10,
                    ),
                ),
                ("cover_png", models.BinaryField(blank=True, null=True)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "published_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="news.jamiitekservice",
                    ),
                ),
                (
                    "batch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="articles",
                        to="news.newsbatch",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "category", "-published_at"],
                        name="news_articl_status_0472d0_idx",
                    )
                ],
            },
        ),
    ]
