# Generated by Django 5.2.3 on 2026-10-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_seed_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_thumb",
            field=models.BinaryField(
                blank=True, help_text="720px WebP for cards", null=True
            ),
        ),
    ]
