# Generated by Django 5.2.3 on 2026-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0004_backfill_thumbs"),
    ]

    operations = [
        migrations.AlterField(
            model_name="article",
            name="cover_thumb",
            field=models.BinaryField(
                blank=True,
                help_text="Text-free 1200px WebP for on-site images",
                null=True,
            ),
        ),
    ]
