# Generated by Django 5.2.3 on 2026-10-02 15:42

import news.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_thumb_help"),
    ]

    operations = [
        migrations.AddField(
            model_name="article",
            name="cover_art",
            field=models.FileField(
                blank=True,
                help_text="Text-free 1200px WebP for on-site images — in the bucket",
                max_length=300,
                upload_to=news.models.cover_path,
            ),
        ),
        migrations.AddField(
            model_name="article",
            name="cover_image",
            field=models.FileField(
                blank=True,
                help_text="1200x630 PNG with headline (Open Graph / Discover) — in the bucket",
                max_length=300,
                upload_to=news.models.cover_path,
            ),
        ),
    ]
