# Generated by Django 5.2.3 on 2025-07-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_menstrualcyclerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('food', 'Food'), ('business', 'Business'), ('love', 'Love'), ('debt', 'Debt'), ('transport', 'Transport'), ('entertainment', 'Entertainment'), ('bills', 'Bills'), ('health', 'Health'), ('education', 'Education'), ('other', 'Other')], max_length=50),
        ),
    ]
