# Generated by Django 5.2.3 on 2026-08-29 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_agent_approvals"),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number the agent sends to, e.g. 255629712678', max_length=20, null=True),
        ),
    ]
