# Generated by Django 5.2.3 on 2026-10-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0008_alter_profile_whatsapp_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="goal",
            name="kind",
            field=models.CharField(
                choices=[
                    ("manual", "I update progress myself"),
                    (
                        "monthly_savings",
                        "Monthly savings (income − expenses, automatic)",
                    ),
                ],
                default="manual",
                help_text="Monthly savings goals track themselves from your income and expenses",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="expense",
            name="category",
            field=models.CharField(
                choices=[
                    ("food", "Food"),
                    ("transport", "Transport"),
                    ("entertainment", "Entertainment"),
                    ("bills", "Bills"),
                    ("health", "Health"),
                    ("education", "Education"),
                    ("business", "Business"),
                    ("love", "Love"),
                    ("debt", "Debt"),
                    ("beauty", "Beauty"),
                    ("savings", "Savings / investment"),
                    ("other", "Other"),
                ],
                max_length=50,
            ),
        ),
    ]
