# Generated by Django 5.2.3 on 2026-10-07 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_monthly_savings_goal"),
    ]

    operations = [
        migrations.AddField(
            model_name="approvalrequest",
            name="external_ref",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
